### ISSUE TITLE
Two of the issues reported on free5gcstage3 are not fully merged

### ISSUE THREAD

**Issue by sudhir-intc** [free5gc/free5gc#10]
For the two issues I had reported
1. https://github.com/free5gc/free5gc-stage-3/issues/4 : Readme points to incorrect location for the git clone #4
2. https://github.com/free5gc/free5gc-stage-3/issues/3 : Build failure seen in upf while building libgtp5gnl  - The build failure is fixed but the change done in PR#https://github.com/free5gc/free5gc-stage-3/pull/5 for the testgtpv1 is not merged.

**Comment by free5gc-org** [comment]
Hi,

For [free5gc/free5gc-stage-3#4](https://github.com/free5gc/free5gc-stage-3/issues/4), because we turn out to use free5gc/free5gc as our only repo, we have fix the git clone path issue in [free5gc README](https://github.com/free5gc/free5gc/blob/master/readme.md)

**Comment by free5gc-org** [comment]
For PR#[free5gc/free5gc-stage3#5](https://github.com/free5gc/free5gc-stage-3/pull/5), we are thinking about waiting for @tf-enya to help us re-open the PR here. Due to the different git history, it seems that we cannot just format-patch the PR here.

Or if there is any good idea or comment is welcomed!
