### ISSUE TITLE
TestRegistration Script Failure due NGAP SCTP segmentation fault

### ISSUE THREAD

**Issue by Prema-NA** [free5gc/free5gc#107]
## Describe the bug
TestRegistration Script Failure due NGAP SCTP segmentation fault

## To Reproduce
1.Followed the installation procedure as per https://www.free5gc.org/stage-3-free5gc
2. Change config 'no Config Changes'
3. Code patch 'v3.0.3' 
4. Run command './run.sh, ./test.sh TestRegistration'
5. Dump packet 'tcpdump -i any -w Registration1.pcap'

## Expected behavior
Registration Procedure to be successful

## Environment (please complete the following information):
 - free5GC Version: v3.0.3
 - OS: Ubuntu 18.04 Server
 - Kernel version:5.0.0-23-generic
 - go version:1.14.4 linux/amd64
 - c compiler version (Option):  gcc version 7.3.0

PCAP, LOGS and Config files are uploaded as LOGS.tar file

[5GC-Logs.zip](https://github.com/free5gc/free5gc/files/5207728/5GC-Logs.zip)

**Comment by free5gc-org** [comment]
You have got the error "GTP device named upfgtp0 Create fail" and "Error parsing ServerIPv4 address as string. Using the 0.0.0.0 address as default."

Do you insert gtp5g module successfully? Are you code using latest version instead of v3.0.3?

I don't think this is a bug but some config error. Please close the issue and search for the issue first or discuss it on [the forum](https://forum.free5gc.org)
