### ISSUE TITLE
Need information on up_resource_ip present in SMF ULCL configuration

### ISSUE THREAD

**Issue by sudhir-intc** [free5gc/free5gc#13]
Hi,
I am trying to use ULCL functionality. While going the reference SMF ULCL configuration file, I found the entries related to up_resource_ip as below. I wanted to know what purpose these IP addresses are used, tried checking the code but I see these attributes are not being referred. The UPNode struct has no mappings for up_resource_ip.

userplane_information:
    up_nodes:
      gNB1:
        type: AN
        an_ip: 192.188.2.3
      BranchingUPF:
        type: UPF
        node_id: 10.200.200.102
        up_resource_ip: 192.188.2.2
      AnchorUPF1:
        type: UPF
        node_id: 10.200.200.101
        up_resource_ip: 192.188.2.23
      AnchorUPF2:
        type: UPF
        node_id: 10.200.200.103
        up_resource_ip: 192.188.2.24

**Comment by free5gc-org** [comment]
Hi,

This is a pre-configure resource for UP bind address (gtp server binding address). This was not use due to the UPF will reply an UP Function.

Accurately we should put it to the UP resource than replace UP resource by UP Function if UPF Association reply exist this IE. But we didn't do it yet. If you are interesting in it, it's welcome to contribute. 😄

So you can view it as no used feature.

**Comment by sudhir-intc** [comment]
Thanks for this information

**Comment by sudhir-intc** [comment]
Attaching the pcaps from the three UPF's
[ulcl_upfs_pcap.zip](https://github.com/free5gc/free5gc/files/4488684/ulcl_upfs_pcap.zip)
