### ISSUE TITLE
[Bugs] AMF is not requesting the retransmission of the Registration Request message

### ISSUE THREAD

**Issue by bertuola** [free5gc/free5gc#149]
## Describe the bug
AMF is not requesting the retransmission of the **Registration Request** message after security context has been established.

## To Reproduce
1. Basic configuration
2. Real gNB and UE, or simulator
2. Run standard registration procedure

## Expected behavior
In the **Security Mode Command** message, in **Additional 5G Security Information** in NAS part, the AMF shall request the retransmission of the original NAS message (Registration Request).

**Reference: 3GPP 24.501**

Section 5.5.1.2.2 Initial registration initiation, it is specified that: "_If the UE does not have a valid 5G NAS security context, the UE shall send the REGISTRATION REQUEST message without including the NAS message container IE. The UE shall include the entire REGISTRATION REQUEST message (i.e. containing cleartext IEs and non-cleartext IEs, if any) in the NAS message container IE that is sent as part of the SECURITY MODE COMPLETE message as described in subclauses 4.4.6 and 5.4.2.3._"

Section 5.4.2.2 NAS security mode control initiation by the network, it is specified that: "_If, during an ongoing registration procedure, the AMF is initiating a SECURITY MODE COMMAND (i.e. after receiving the REGISTRATION REQUEST message, but before sending a response to that message) and: a) the REGISTRATION REQUEST message does not successfully pass the integrity check at the AMF; or b) the AMF can not decipher the value part of the NAS message container IE in the REGISTRATION REQUEST message; the AMF shall include the Additional 5G security information IE with the RINMR bit set to "Retransmission of the initial NAS message requested" in the SECURITY MODE COMMAND message requesting the UE to send the entire REGISTRATION REQUEST message in the SECURITY MODE COMPLETE message as described in 3GPP TS 33.501 [24]._"

## Screenshots

**Correct Behaviour**

![image](https://user-images.githubusercontent.com/19303811/101772893-4d63a180-3aec-11eb-82fd-87c2b65590e3.png)

**free5gc's AMF**

![image](https://user-images.githubusercontent.com/19303811/101773774-85b7af80-3aed-11eb-9905-b8ecd145b346.png)

## Environment (please complete the following information):
 - free5GC Version: 3.0.4
 - OS: [e.g. Ubuntu 200.04 Server]
 - Kernel version: 5.4.0-53-generic
 - go version: go1.14.4 linux/amd64

### PCAP File

[free5gc_Missing_2nd_Registration_Request.zip](https://github.com/free5gc/free5gc/files/5672775/free5gc_Missing_2nd_Registration_Request.zip)

**Comment by free5gc-org** [comment]
TS 24.501 Section 5.4.2.2 said that: AMF shall set RINMR bit when **the REGISTRATION REQUEST message does not successfully pass the integrity check at the AMF**.

But in initial registration procedure, the UE & AMF have not establish any NAS security context, so the integrity check didn't be triggered and the condition **does not successfully pass the integrity check** is not fulfilled (because integrity protection is not enable at this moment). As a result, AMF would not set RINMR bit.

TS 24.501 Section 5.4.2.3 said that: **If, prior to receiving the SECURITY MODE COMMAND message, the UE without a valid 5GS NAS security context had sent a REGISTRATION REQUEST message the UE shall include the entire REGISTRATION REQUEST message in the NAS message container IE of the SECURITY MODE COMPLETE message as described in subclause 4.4.6.**

So in initial registration, we think that the UE should include the entire registration request inside the security mode complete which is described at section 5.4.2.3. And RINMR bit is used in the other case like mobility registration procedure, service request procedure, etc.

**Comment by bertuola** [comment]
In all the examples I have (with simulators and/or real cases), the AMF sets the RINMR bit for instructing the UE to re-send the REGISTRATION REQUEST. In my understanding, the UE doesn't send it if not explicitly requested by AMF.

**Comment by YouShengLiu** [comment]
> Section 5.4.2.2 NAS security mode control initiation by the network, it is specified that: "If, during an ongoing registration procedure, the AMF is initiating a SECURITY MODE COMMAND (i.e. after receiving the REGISTRATION REQUEST message, but before sending a response to that message) and: a) the REGISTRATION REQUEST message does not successfully pass the integrity check at the AMF; or b) the AMF can not decipher the value part of the NAS message container IE in the REGISTRATION REQUEST message; the AMF shall include the Additional 5G security information IE with the RINMR bit set to "Retransmission of the initial NAS message requested" in the SECURITY MODE COMMAND message requesting the UE to send the entire REGISTRATION REQUEST message in the SECURITY MODE COMPLETE message as described in 3GPP TS 33.501 [24]."

It seems that the two conditions for letting AMF set the RINMR bit to 1 won't be satisfied.
1. The REGISTRATION REQUEST message does not successfully pass the integrity check at the AMF.
    - Since the REGISTRATION REQUEST is a plain NAS message, AMF won't do an integrity check on it.
2. The AMF can not decipher the value part of the NAS message container IE in the REGISTRATION REQUEST message.
    - The REGISTRATION REQUEST even doesn't contain the NAS message container.
  
Therefore, It seems quite reasonable that the AMF sets the RINMR bit to 0 in the SECURITY MODE COMMAND message.
