### ISSUE TITLE
TestRegistration not working on a fresh install of v3.0.5[Bugs]

### ISSUE THREAD

**Issue by vineet-rarisystems** [free5gc/free5gc#166]
## Describe the bug
Installed the latest version of free5gc according to installation steps.
running ```sudo ./test.sh TestRegistration``` 
The error says "Nausf_UEAU Authentication Request Error: server no response"

## To Reproduce
1. follow [installation steps](https://github.com/free5gc/free5gc/wiki/Installation) to install v3.0.5 free5gc
2. run ```sudo ./test.sh TestRegistration``` 

## Expected behavior
The test is expected to succeed

## Screenshots
![testreg error](https://user-images.githubusercontent.com/71391687/106374811-58300980-63ac-11eb-83c9-926a7a338d14.JPG)

## Environment (please complete the following information):
 - free5GC Version: v3.0.5
 - OS: Ubuntu 18.04
 - Kernel version:5.0.0-23-generic
 - go version:1.14.4 linux/amd64

**Comment by jay16213** [comment]
Please drop your mongoDB and then test again

```bash
mongo -eval "db.dropDatabase()" free5gc
```

This is because free5gc has change the default IP config for NFs at v3.0.5,
and your mongoDB may have some outdated NF profile with old IP, which is returned by NRF to NF consumer, e.g. AMF.

BTW, you don't need to run test.sh with sudo. Just type `./test.sh` and test.sh will check the root permission then run the command with sudo if need automatically.

**Comment by vineet-rarisystems** [comment]
Thanks, it worked!
