### ISSUE TITLE
UPF crashing with `bufPool64 is empty` error.

### ISSUE THREAD

**Issue by endrigoshi** [free5gc/free5gc#17]
I am actually running stage-2 but I saw that this part of the code is not updated for the stage-3 so that's why I'm reporting it here.
When establishing multiple sessions in the UPF, e.g. by running the Registration test multiple times (while the NFs are initialized only once), the UPF crashes when it's supposed to receive the 9th `SessionEstablishmentRequest`. If the UPF is that rerun, the SMF will continue by sending a request with `FAR_ID=10`, and the UPF will again crush upon receiving the 9th consecutive `SessionEstablishmentRequest`. 
The error is as follows:
`ERRO[2020-04-20T19:35:28Z] c/upf/lib/utlt/src/utlt_buff.c:80 SelectBufblkOption() bufPool64 is empty  UPF=Util Segmentation fault`

I would suspect that the size of the available buffers is hard-coded somewhere (maybe in `utlt_buff.c`) but the source code of that file is not available and therefore I couldn't confirm it.

Anyway, can you confirm whether this behavior is intentional or is it a bug?

**Comment by free5gc-org** [comment]
hi @endrigoshi ,

Yes, in stage 2 there are some bugs about freeing the buffer. And that is due to the timeout mechanism failed.
We fix this issue in stage 3 so maybe you can test it again using stage 3's code.
If there still remind same issue, feel free to report to us with maybe some log and pcap. We'll double check with it.

Thanks a lot

**Comment by endrigoshi** [comment]
From my initial testing, the issue seems to have been fixed.

Will close the issue for now.
