### ISSUE TITLE
[Feat] Key Performance Indicator Metrics (Prometheus)

### ISSUE THREAD

**Issue by infinitydon** [free5gc/free5gc#175]
## Issue Description
I think it might be good to include some performance metrics e.g. Prometheus metrics. This will provide an opportunity to have a dashboard that shows how the free5gc deployment is behaving.

### What's the version are you using
Not related to a particular free5c version.

### Is your feature request related to a problem? Please describe.
No it is not

### Describe the solution you'd like
- Free5gc components (amf,smf,pcf,upf etc.) generate metrics that can be scrapped (e.g. Prometheus).
- Example of metrics will be Attach Failure/Success Rate, Number of UEs, Number of GnB, Bearer statistics etc.
- Metrics can now be used to create dashboards (e.g. Grafana).

### Describe alternatives/workarounds you've considered
I don't think there is an existing solution for this with regards to free5gc.

### If willing to resolve an issue by submitting Pull request, please consider the points below.

I don't know how to write programs currently. I opened this case maybe it might be interesting for the community to consider it.

**Comment by raoufkh** [comment]
Hello @infinitydon 

We are working on the deployment of Free5GC on Kubernetes using Helm charts.

We have been able to monitor the Free5GC components using Prometheus.

For resource usage monitoring, it helped us to define resource requests and limits for the Free5GC components. Please [see](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/).

For application-specific metrics, we've used the [istio](https://istio.io/) service mesh to do the instrumentation. For the control plane components, we could have more grained metrics by using this feature for [customizing metrics](https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/) provided by Istio.

The same feature is provided by another service mesh called [linkerd](https://linkerd.io/ in [a more automated way](https://linkerd.io/2/tasks/getting-per-route-metrics/). You will can see that you can customize http metrics based on OpenAPI files. For Free5GC, [OpenAPI] are available [here](https://github.com/free5gc/openapi). 

NOTE: I've not tried yet to customize metrics which would allow to get a per path metrics instead of having a single http_request metric.

Furthermore, service meshed can help also in generating traces that will be consumed by [Jaeger](https://www.jaegertracing.io/) for example.

What I am telling you after listing the possibilities offered to generate KPIs is that it is not a priority I think. I think we should rather think about having a stable version of Free5GC on Kubernetes (it will be the platform that host 5g networks sure) and then switch to a [microservice architecture](https://medium.com/hashmapinc/the-what-why-and-how-of-a-microservices-architecture-4179579423a9) for the next versions. This cannot be done without opening a discussion between the developers of the Free5GC code and the operational staff who need to deploy 5G in open source platforms. I think that such an initiative could take this project much forward.

For the Helm charts, they are available for versions 3.0.4 and 3.0.5. We offer also the possibility of establishing an end to end testing using the [UERANSIM](https://github.com/aligungr/UERANSIM). We have to verify if we're allowed to publish them in Github (in terms of licenses) before doing it :(

Best regards,
Abderaouf

**Comment by infinitydon** [comment]
Hi @raoufkh,

Thanks for the response..

Actually examples of the metrics that I am suggesting are:
- Number of Attached Users
- Attach Failure/Success Rate
- Number of attached gNbs
- Bearer activations/deactivations
- utilization of the UE IP pools (how many UE IPs have been allocated, how many are free).

Can you confirm if the service mesh observability approach will provide the kind of metrics I listed above?

I also work on k8s and am a huge fan of provisioning 5GC using k8s, I have also made some suggestions with regards to deploying free5gc ion k8s. Using k8s will certainly fulfill one of the mantra of 5GC since it positioned to be deployed a  Cloud Native Functions.

kindly let us know peradventure your k8s implementation will be made open-source.

**Comment by raoufkh** [comment]
I agree with you that service meshes provide more advanced metrics only for HTTP traffic. So you can have metrics like the number of registration requests to the NRF , number of PDU sessions created by the SMF... etc. This allows developpers to minimize the need of changes in the application code.

I'm looking forward to the agreement to make the project open source so that the community can have a very simple method to deploy and configure Free5GC on Kubernetes and I'll let you know about it. I also hope to be able to have discussions with Free5GC contributors to talk about possible improvements of NFs (more desgin side).

Publishing in open source would also allow to improve Helm charts by benefiting from the experiences of others.

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

https://forum.free5gc.org/t/is-it-possible-to-create-a-node-just-to-measure-performance/732/4

**Comment by boeboe** [comment]
+1

FYI, I have been setting up Free5GC with Istio, Prometheus en ELK stack successfully, so I would be more the interested and willing to help out, also on the Helm aspects of it.

**Comment by ritokispingvin** [comment]
Hi @boeboe, @raoufkh,

I was trying to setup Prometheus with free5GC, but after installing Prometheus I'm a little lost how to proceed further, what files do I need to modify and how, to tell Prometheus what metrics should he monitor.
As you've been able to setup Prometheus with free5GC succesfully, could you help me out with some tips/tutorials which could help me to proceed? Or if it's possible to share some codes here or on GitHub, I would really appreciate that.
Unfortunately I'm not really experienced with programming, expecially not with Golang yet.

To start off, I would like to supervise more or less the same metrics @infinitydon mentioned on Feb 14th. Later I would like to also add custom metrics but as I understood from @raoufkh's comment I will need service meshes for that (Istio).

**Comment by boeboe** [comment]
I am using Istio. Istio ships with dashboard for sidecar and cluster metrics. Next to that I've installed Prometheus node-exporter to gain visibility on node consumption per microservice. 

If you want extra metrics for F5GC specifically, you would need to annotate your F5GC deployments and implement a /metrics endpoint in the microservice yourself, but the metrics provided by Istio and node-exporter gave me enough information.

**Comment by ritokispingvin** [comment]
Thanks @boeboe for your comment! I've managed to setup Prometheus and node exporter. 
For Istio, I see that it requires Kubernetes cluster which is still under deployment for free5GC, as per @raoufkh's earlier comment.
Can you help me how did you overcome this issue? It's the ELK stack which you've mentioned?

**Comment by boeboe** [comment]
You can deploy free5gc on kubernetes already, given you enable sctp support as an api-server experimental flag. You also need a CNI plugin with multi network interface support for the non-http traffic between ue/gnbsim/amf/smf. I used multus in my example. 

https://github.com/boeboe/free5gc-k8s

ELK is the abbreviation of the popular logging stack solution from Elastic, being  ElasticSearch, Logstash & Kibana. I use it to send the log streams of the CNFs to ElasticSearch and create Kibana dashboards for visualizations.

**Comment by raoufkh** [comment]
Hello @boeboe 
> For distributed tracing (with Zipkin, Jaeger or OpenTracing), the CNF's would have to copy the correct tracing headers so that spans can be generated to trace the call throughout different CNF's.
> 
> https://istio.io/latest/faq/distributed-tracing/
> 
> A very simple POC of this:
> 
> https://github.com/boeboe/goserver-scratch/blob/69a8d3c9bfa9f7399fba39dd8e6fb9c87ac87ba8/goserver/main.go#L110
> 
> **UPDATE:** Looks like the headers are already propagated:
> https://github.com/free5gc/http_wrapper/blob/29c8b0c4241fbae21255e8b569a0677841884ae9/request.go

What about tracing non HTTP calls. In the context of 5G we may have to trace requests that are not based on HTTP but other protocols like NGAP, PFCP ... etc

I know that Jaeger introduce the calls to databases in traces even if the protocol used to communicate with these databases is not HTTP

**Comment by raoufkh** [comment]
Yes ! Even the Envoy proxies they don't intercept UDP traffic, often used as the transport protocol for PFCP (SMF-UPF) and GTP (gNB-UPF) and they do not talk about SCTP which is used for NGAP (gNB-AMF). There is a clear need for a 5G service mesh :D

**Comment by raoufkh** [comment]
Hello again
I was finally able to publish the project on github. I let you discover: https://github.com/Orange-OpenSource/towards5gs-helm
I put the documentation and tutorials in the [docs](https://github.com/Orange-OpenSource/towards5gs-helm/tree/main/docs) folder and I remain at your disposal if you need.

**Comment by lgabhishek18** [comment]
> Hi @raoufkh,
> 
> Thanks for the response..
> 
> Actually examples of the metrics that I am suggesting are:
> 
> * Number of Attached Users
> * Attach Failure/Success Rate
> * Number of attached gNbs
> * Bearer activations/deactivations
> * utilization of the UE IP pools (how many UE IPs have been allocated, how many are free).
> 
> Can you confirm if the service mesh observability approach will provide the kind of metrics I listed above?
> 
> I also work on k8s and am a huge fan of provisioning 5GC using k8s, I have also made some suggestions with regards to deploying free5gc ion k8s. Using k8s will certainly fulfill one of the mantra of 5GC since it positioned to be deployed a Cloud Native Functions.
> 
> kindly let us know peradventure your k8s implementation will be made open-source.

Hi, 

I am also looking for these metrics, I have deployed Free5gc with Ueransim from [Orange-Opensource towards5gs](https://github.com/Orange-OpenSource/towards5gs-helm) helm charts. 
If you have got any concrete solution then please let me know.

Thanks!!

**Comment by raoufkh** [comment]
Hi @lgabhishek18 

The KPIs you are looking for are very specific to 5G and I don't think there is a service mesh solution that can provide them (at lease Istio, Linkerd, and most popular service mesh tools don't). I've devlopped a tool using eBPF to get 5G-related metrics. All the metrics you mentioned except Bearer activations/deactivations and utilization of the UE IP pools are possible to get using Prometheus queries). For the two last metrics, I ignore if it is possible to get them with our current implementation.  Our work has been published in https://ieeexplore.ieee.org/abstract/document/10154433 and https://ieeexplore.ieee.org/document/10154369. The proposed solution has been tested with free5GC and Open5GS. You can find more details in the papers. We have the intent to make the code avaialable but unfortunately, the solution is not yet documented.

Regards,
Abderaouf

**Comment by ianchen0119** [comment]
Hi @lgabhishek18 

The simple way is to implement a custom Prometheus metrics exporter, then you can edit your alert rule and get the specific report.

Hi @raoufkh 
If you need any technical help to integrate your project with the free5GC, please let me know.
Thanks.

**Comment by lgabhishek18** [comment]
Hi @ianchen0119 

I appreciate your response. I have tried to create the custom Prometheus metric exporter, but I think that Free5GC doesn't provide metrics that can be scraped by Prometheus. Can you elaborate more on your approach?

To provide further insight into my current situation, I have setup Free5GC on Kubernetes, and my goal is to monitor telco-specific metrics. These metrics include essential KPIs such as the number of connected UEs (User Equipments), Attach Success Rate, Attach Attempts, the count of gNBs and more.
I am still exploring the best solution that can solve my issue.

Reagards!!
Abhishek

**Comment by ianchen0119** [comment]
Hi @lgabhishek18 
Sorry for the late reply.
There is an example to implement the simple metrics exporter in the Network Function:
https://github.com/ianchen0119/amf/tree/feat/prom
I think you can refer to this example to develop the solution by yourself.
