### ISSUE TITLE
[Bugs] subscriber's IMEI requested in clear if not provided in NAS Security Mode Complete

### ISSUE THREAD

**Issue by p1-bmu** [free5gc/free5gc#195]
## Describe the bug
During the NAS protocol exchange between the UE and the AMF, when the UE does not provide its IMEI directly in the Security Mode Complete, the AMF requests it in clear-text whereas the NAS security context has been established successfully. This contradicts the 3GPP specification on NAS TS 24.501, sections 4.4.4.1 and 4.4.4.2.
This issue may expose 5G subscribers' IMEI in clear-text over the radio interface, in case their handsets are failing to support properly the sending of the IMEI within the Security Mode Complete. 

## To Reproduce
No easy way to reproduce with available open-source tools. A modification of a gNB / UE emulator can be done to answer Security Mode Control in a custom way, by not providing the IMEI in the message: this will trigger the AMF to then request IMEI in the clear.

## Expected behavior
IMEI shall never be requested in clear text NAS messages.

## Environment (please complete the following information):
 - free5GC Version: v3.0.5
 - OS: Ubuntu 20.04
 - Kernel version: 5.4.0-62-generic
 - go version: go1.14.4 linux/amd64  

### Configuration File
No specific configuration required.

### PCAP File
A pcap is provided with 2 successive NAS registration, where this insecure behavior is exhibited during the 2nd registration.
[free5gc_nas-smc_imei-in-clear.pcap.gz](https://github.com/free5gc/free5gc/files/6376663/free5gc_nas-smc_imei-in-clear.pcap.gz)

### Log File
No specific log exists for this issue.

**Comment by ianchen0119** [comment]
@p1-bmu 

Thanks for your contributions.

For your report, I have a little confused.

From my perspective, I think this issue may isn't a bugs to AMF:
1\.  Step 11 of Registration procedure, described in 3GPP TS 23.502:
> The PEI shall be transferred encrypted unless the UE performs Emergenct Registration and cannot be authenticated.

I suppose the problem is caused by you modified the UE emulator, so UE transferred the PEI as a cleartext.

2\. quote from TS 24.501 sections 4.4.4.1 and 4.4.4.2:
> For the network, integrity protected signalling is mandatory for the 5GMM NAS messages once a secure exchange of 5GS NAS messages has been established for the NAS signalling connection.

It's required the integrity protection on exchange of 5GS NAS message, the encryption is [not mandatory](https://github.com/free5gc/free5gc/issues/208).


If possible, could you clearly explain on contradicts you mentioned above or any further information for your perspective?
Thanks again.

**Comment by jordan0210** [comment]
Hi @p1-bmu ,

According to 5.4.3.3 in TS 24.301, UE shall encrypt all NAS messages after it sends security mode complete whether it receives ciphered or unciphered messages. So you may have some bugs in your UE/RAN. You may use [UERANSIM](https://github.com/aligungr/UERANSIM) to do your test. It will cipher all NAS messages after it sends security mode complete.

The PR above fixes the AMF sends unciphered identity request after it receives security mode complete message.

Thank you for your contributions.
