### ISSUE TITLE
Docker Image With Kernel 5.0.0-23-generic

### ISSUE THREAD

**Issue by infinitydon** [free5gc/free5gc#30]
Hi,

Please is there a way to get an ubuntu docker image with kernel `5.0.0-23-generic` since this is needed by the gtp-u for the UPF component? Or if you have a sample Dockerfile for the UPF software release 3.0.1?

Thanks

**Comment by free5gc-org** [comment]
Hi,

For our notice, docker is a virtualization technique base on namespace. One of its benefit compare with vm is the light weight due to its sharing kernel with host. But that also means it cannot run on the different kernel from your host OS.
So if you need to run UPF in a container, your host OS must have `5.0.0-23-generic` version of kernel. In that case, you can run the UPF successfully inside a container.

For more details, you can also reference to [stackoverflow](https://stackoverflow.com/questions/32841982/how-can-docker-run-distros-with-different-kernels).

BR

**Comment by bjoern-r** [comment]
on a plain ubuntu 18.04 with linux-image-generic-hwe-18.04-edge kernel 5.3.0-36 is installed and there gtp5g works.

**Comment by free5gc-org** [comment]
That's true, because the kernel and kernel module is share between container and host.

Thanks a lot!

**Comment by infinitydon** [comment]
Understood, was a bit confused with the specific kernel requirement, image building for the UPF works now.
