### ISSUE TITLE
UE attach to free5gc, fail in  resynchronization process

### ISSUE THREAD

**Issue by chenhao5651** [free5gc/free5gc#33]
I use 5G UE conntect to free5gc, but it fail in resynchronization process. I checked the source code. In funtcion HandleGenerateAuthData, UDM get SQN from MogoDB every time. In resynchronization process UDM should get SQN from UE and update it to UDM.

**Comment by free5gc-org** [comment]
Thanks for the report. We'll check the bug.

**Comment by 359859461** [comment]
how's going about this issue?we get same problem

**Comment by chenhao5651** [comment]
> 
> 
> how's going about this issue?we get same problem

Free5gc still have this problem. I've fixed this bug.

**Comment by 359859461** [comment]
could you share it to us

**Comment by chenhao5651** [comment]
> 
> 
> could you share it to us
The main changes is in the HandleGenerateAuthData
[generate_auth_data.zip](https://github.com/free5gc/free5gc/files/4768548/generate_auth_data.zip)

**Comment by 359859461** [comment]
udm crashed when i start the registration request(after replaced the "generate_auth_data.go")

INFO[2020-06-12T06:17:51Z]/src/udm/udm_producer/generate_auth_data.go:35 free5gc/src/udm/udm_producer.HandleGenerateAuthData() supi conversion => imsi-460070123456001       UDM=UEAU
https://127.0.0.1:29510
INFO[2020-06-12T06:17:51Z]/src/udm/udm_producer/generate_auth_data.go:98 free5gc/src/udm/udm_producer.HandleGenerateAuthData() HandleGenerateAuthData AUTS is =%!s(*models.ResynchronizationInfo=<nil>)  UDM=UEAU
INFO[2020-06-12T06:17:51Z]/src/udm/udm_producer/generate_auth_data.go:186 free5gc/src/udm/udm_producer.HandleGenerateAuthData() K=1234567890abcdef1111111111111111
SQN=16f3b3f70fc2
OP=12345678901234561234567890123456
OPC=  UDM=UEAU
INFO[2020-06-12T06:17:51Z]/src/udm/udm_producer/generate_auth_data.go:198 free5gc/src/udm/udm_producer.HandleGenerateAuthData() RAND=1d57925162bd4fe61d245311e613fc39
AMF=8000  UDM=UEAU
panic: runtime error: index out of range

goroutine 62 [running]:
free5gc/lib/milenage.milenageF1(0x12c85f0, 0x0, 0x0, 0xc00002b260, 0x10, 0x20, 0xc0002c0890, 0x10, 0x10, 0xc0002c0840, ...)
        /root/go/src/free5gc/lib/milenage/milenage.go:60 +0x3fb
free5gc/lib/milenage.F1_Test(...)
        /root/go/src/free5gc/lib/milenage/milenage.go:577
free5gc/src/udm/udm_producer.HandleGenerateAuthData(0xc0007d4000, 0xc00011248e, 0x1e, 0x0, 0x0, 0xc000296940, 0x20, 0x0, 0xc00012a030, 0x24)
        /root/go/src/free5gc/src/udm/udm_producer/generate_auth_data.go:213 +0x17ad
free5gc/src/udm/udm_handler.Handle()
        /root/go/src/free5gc/src/udm/udm_handler/handler.go:39 +0x5f4
created by free5gc/src/udm/udm_service.(*UDM).Start
        /root/go/src/free5gc/src/udm/udm_service/udm_init.go:146 +0x57b
root@user:~/go/src/free5gc#

**Comment by adejavel** [comment]
Hello,
We had the same issue in our lab, which is due to two different issues that we have fixed:
* The first one is that AUSF doesn't send resynchronisation informations received from AMF to UDM so UDM doesn't try to resynchronize... To fix this issue, we added the following line in file `src/ausf/producer/ue_authentication.go` after line 187 : `authInfoReq.ResynchronizationInfo = body.ResynchronizationInfo`
* The second issue is that resynchronization is not implemented by free5gc UDM currently... We first replaced the file `src/udm/producer/generate_auth_data.go` by the the file provided by @chenhao5651 . The file is great but not implementing well the resynchronization procedure as the UE should not send back RAND but only AUTS so UDM has to find itself the RAND used to generate previous authentication vectors. So the code provided doesn't work with commercial equipments. The UDM should retrieve RAND from database. We didn't implemented this but we made a workaround with a hard coded RAND. In the file provided by @chenhao5651 , comment line 191, copy line 195 and paste it above line 99. Then change line 103 from `RAND_ms,_ :=  hex.DecodeString(RAND_ms_str)` to ` RAND_ms :=  RAND`

This makes resynchronization procedure working but it is still a workaround !

**Comment by 359859461** [comment]
@adejavel 



we have fix the plan offered by@chenhao5651 
1.replace “generate_auth_data.go” （we do a few change）
2.Add  following line in ausf/ausf_producer/UEAuthentication.HandleUeAuthPostRequest：
if body.ResynchronizationInfo != nil {authInfoReq.ResynchronizationInfo = body.ResynchronizationInfo}
（same with @adejavel ）
3.Add following line in amf/gmm/gmm_handler/handler.HandleAuthenticationFailure（after line 2067）：
var av5gAka models.Av5gAka
if err := mapstructure.Decode(ue.AuthenticationCtx.Var5gAuthData,&av5gAka);err != nil {return fmt.Errorf("Var5gAuthData Convert Type Error")}
auts := authenticationFailure.AuthenticationFailureParameter.GetAuthenticationFailureParameter()
resynchronizationInfo := &models.ResynchronizationInfo{Rand:av5gAka.Rand,Auts: hex.EncodeToString(auts[:]),}

**Comment by 359859461** [comment]
[generate_auth_data.zip](https://github.com/free5gc/free5gc/files/4797759/generate_auth_data.zip)

**Comment by free5gc-org** [comment]
Seems still happened

**Comment by adejavel** [comment]
Hello,
We tested the fix proposed by @359859461 and it is working well ! thanks

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

https://forum.free5gc.org/t/does-free5gc-support-real-gnb-and-5g-ue/176/2

**Comment by free5gc-org** [comment]
Hello everyone,
in v3.0.4 we add a test with resynchronization process (`./test.sh TestReSynchronisation`)
and we think this bug has been fixed in v3.0.4
You can upgrade free5gc to the latest version and test if this problem is still exist
