### ISSUE TITLE
[Question] Can free5gc support multiple  AMF

### ISSUE THREAD

**Issue by ayoub-tl** [free5gc/free5gc#412]
Can free5gc support multiple  AMF, and can the the selection based on NSSAI ?

**Comment by JiMMyMatrix** [comment]
Hi,
The answer of first question is yes. You need to create amfcfg.yaml for each AMF and modify the parameter in yaml files. In yaml file, there are 'ngapIplist' 'sbi' terms, you might change them into proper address. More information you can check [this](https://medium.com/@ben0978327139/5g-sctp-loadbalancer-using-loxilb-applying-on-free5gc-b5c05bb723f0).

And the second question, we can't ensure that selecting AMF based on NSSAI could success. Since according to 3gpp spec, AMF selection is done by ran. If you are using [UERANSIM](https://github.com/aligungr/UERANSIM), you might ask them for more information.

Additional information, free5GC has implemented old to new AMF exchange based on UE registration of spec 23.502, it contains NSSAI checking. However we don't have written test file for procedure yet, it will be completed soon.
