### ISSUE TITLE
during UE DoS, UPF stop create PDU session

### ISSUE THREAD

**Issue by zbh888** [free5gc/free5gc#438]
Hello free5GC team.

I am trying to perform a DoS attack. And I want to make sure the system is working when I turn on and turn off one UE multiple times.

I am using the ./nr-ue command to boot a UE and use ./nr-nli -e "deregister switch-off" to turn it off. The interval I set between the operations is 2 seconds.

However, after like 200 times, the UPF stops working(I saw nothing updated in the logs) and UE is simply stuck at [Initial context setup request received]. I used the free5gc-compose v3.2.1. And I can connect 11 UE at the same time. 

Appreciated a lot for any help!

**Comment by ianchen0119** [comment]
Hi @zbh888 

In my opinion,
This test result is acceptable due to free5GC does not guarantee the availability and scalability.

If you think this situation is caused by the potential bugs,
Please help to provide the log file and pcap.

Thanks.

**Comment by zbh888** [comment]
Hello @ianchen0119 . Thank you for the reply. I think this is potentially caused by a bug which might be related to randomness. Sometimes, I can turn on/ switch off like 500 times, and sometimes it is only 100 times. I attached the log of each network function, pcap, and my testing script. Appreciate it a lot if you could take a brief look.
[zbh888.tar.gz](https://github.com/free5gc/free5gc/files/11072905/zbh888.tar.gz)
[zbh888.zip](https://github.com/free5gc/free5gc/files/11072906/zbh888.zip)

**Comment by Bunos07** [comment]
Fix

**Comment by ianchen0119** [comment]
Hi @zbh888 

I notice that you just closed this issue.
Is this issue be solved in release 3.3.0?

Thank you.

**Comment by zbh888** [comment]
@ianchen0119 Sorry, I thought this issue is not watched any more. I didn't do further test but I am also interested what is going on.

**Comment by ianchen0119** [comment]
Hi @zbh888 

@Jerry0666 is responsible for analyzing the root cause of this issue.
We'll update the result here when the issue is solved.

Thanks.

**Comment by Jerry0666** [comment]
Hello! After my test, free5GC will crash, probably because the ue state stored in amf is different from the current state. Therefore, it must be confirmed that ue has been deregistered before registration. I am using general free5gc for testing(not docker-compose, for easier debug). I am attaching my test script here, sometimes the cli command of ueransim will be stuck, but free5gc does not crash, you can try it. Finally, to perform this kind of DOS test, it is better to use more RAM and a better cpu, which is less error-prone.
[dos.zip](https://github.com/free5gc/free5gc/files/12213617/dos.zip)
If you want to check the ue registration status of free5gc, you can use webconsole.
![image](https://github.com/free5gc/free5gc/assets/131638457/5c9a5e67-c732-44fa-b45d-5a33c4c7d824)

**Comment by zbh888** [comment]
Thank you so much for investigating this problem. So the issue is more likely from UERANSIM. However, the UERANSIM is not maintained anymore. I noticed Free5GC team added handover processing although UERANSIM did not. I wonder if there is a better tool than UERANSIM to simulate an end-to-end 5G environment. For example, some tool that can support handover?

**Comment by brianchennn** [comment]
Actually, our team also uses [landslide](https://www.spirent.com/products/core-network-test-5g-lte-ims-wifi-diameter-landslide) to test the functionality, but it's commercial software.

**Comment by zbh888** [comment]
Thank you very much for the info!
