### ISSUE TITLE
[Bugs] ULCL in free5GC v3.4.2 doesn't work

### ISSUE THREAD

**Issue by s5uishida** [free5gc/free5gc#599]
Hi @free5gc-org 

ULCL in free5GC v3.4.2 doesn't work.
However, ULCL([scenario1](https://github.com/s5uishida/free5gc_ueransim_ulcl_sample_config),[scenario2](https://github.com/s5uishida/free5gc_ueransim_ulcl_2_sample_config)) worked fine with the following combination:

- C-Plane - free5GC v3.4.2
- U-Plane - go-upf v1.2.1

A quick note is [here](https://github.com/s5uishida/simple_confirmed_info_for_mobile_network#free5gc).

FYI.

**Comment by s5uishida** [comment]
Alternatively, ULCL may be confirmed with free5GC v3.4.3 using [NextMN-UPF](https://github.com/nextmn/upf) as UPF.

**Comment by andy89923** [comment]
Hi, 

Thanks for reporting this bug. 
Could you describe or print out which part "doesn't work"? Thanks.

**Comment by s5uishida** [comment]
Hi @andy89923 

Thank you for your reply.
[This same issue](https://forum.free5gc.org/t/access-to-local-dn-through-i-upf-in-ulcl-scenario/2512) occurred here.

**Comment by lyz508** [comment]
Hi, @s5uishida,

This issue is caused by the [upf commit](https://github.com/free5gc/go-upf/commit/52fdc334cd68c6f03004ff3a983f3cd926b1a20c) and [smf commit](https://github.com/free5gc/smf/commit/5aab12868188f4311f23cdbe74b9b10b4907c29c#diff-24cc846438b622dc14cd70e67e5de82bf72fc2ae9a2c9181f68807bbaa66f7bd), which changed the ability to swap the destination and source in the flow description from SMF to UPF. After these commits, the source and destination in the flow description of the uplink PDI will be swapped in the UPF. As a result, the uplink PDI of the ULCL pre-config path will be swapped, causing the issue you reported.

We have provided a fix to resolve this issue.

Thank you for your report.

Best regards,
